// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzZlTNEu78XwrZr8IbOrU8N14nZvHmUx8',
    appId: '1:734708237577:web:3237dd222cebacb4cabfd8',
    messagingSenderId: '734708237577',
    projectId: 'mashvira-law-house',
    authDomain: 'mashvira-law-house.firebaseapp.com',
    storageBucket: 'mashvira-law-house.firebasestorage.app',
    measurementId: 'G-L4PJ833M6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9RYT0ffs_OiGoCFEyKhu60SQz62mTD3k',
    appId: '1:734708237577:android:21f5cff0a604877dcabfd8',
    messagingSenderId: '734708237577',
    projectId: 'mashvira-law-house',
    storageBucket: 'mashvira-law-house.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCka1Dh0-klef8Fk3HFaaMbemE0EpM0jCQ',
    appId: '1:734708237577:ios:ee61316059426aa1cabfd8',
    messagingSenderId: '734708237577',
    projectId: 'mashvira-law-house',
    storageBucket: 'mashvira-law-house.firebasestorage.app',
    iosClientId: '734708237577-446ph6sf72pfe5evf9198qa50vanv69i.apps.googleusercontent.com',
    iosBundleId: 'com.law.lawApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCka1Dh0-klef8Fk3HFaaMbemE0EpM0jCQ',
    appId: '1:734708237577:ios:ee61316059426aa1cabfd8',
    messagingSenderId: '734708237577',
    projectId: 'mashvira-law-house',
    storageBucket: 'mashvira-law-house.firebasestorage.app',
    iosClientId: '734708237577-446ph6sf72pfe5evf9198qa50vanv69i.apps.googleusercontent.com',
    iosBundleId: 'com.law.lawApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzZlTNEu78XwrZr8IbOrU8N14nZvHmUx8',
    appId: '1:734708237577:web:18de2ce680b8f7c7cabfd8',
    messagingSenderId: '734708237577',
    projectId: 'mashvira-law-house',
    authDomain: 'mashvira-law-house.firebaseapp.com',
    storageBucket: 'mashvira-law-house.firebasestorage.app',
    measurementId: 'G-EDXTJWZHSY',
  );
}
